### PR TITLE
mod: update to the latest badger/v2 release

### PR DESCRIPTION
**Pull request by mvdan**
(see commit message)

### CODE REVIEW

**Review by aschmahmann — APPROVED** [review]
LGTM, but I actually don't interact with Badger v2 almost at all since it's not bundled with go-ipfs. @Kubuxu any objections?

**Comment by mvdan** [comment]
Even if we feel uneasy about merging this when this is unused/untested, I still think it's best to merge it, because right now master uses a fairly old master commit from badger :)

**Comment by gammazero** [comment]
I thought there was a migration needed for existing data to go from Badger1 to Badger2.  Have we checked whether or not this is the case, and does it mean that once someone upgrades to the new IPFS release, there is no going back?

**Review by gammazero — APPROVED** [review]
Yes, finally.  But are we ever going to use this in IPFS.

**Review by Kubuxu — APPROVED** [review]
In lotus we were using this version of badger either way.

**Pull request merged**
